"""Rename column fix typo

Revision ID: 1ac2eca0f8b7
Revises: 2162eb4efbb8
Create Date: 2016-09-27 23:17:53.987909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac2eca0f8b7'
down_revision = '2162eb4efbb8'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offers', 'required_exerience_months', new_column_name='required_experience_months')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offers', 'required_experience_months', new_column_name='required_exerience_months')
    ### end Alembic commands ###
